configs: configs/datasets/renbody/renbody.yaml

#dataloader_cfg: # we see the term "dataloader" as one word?
dataset_cfg: &dataset_cfg
    data_root: data/renbody/0013_09
    images_dir: images

#val_dataloader_cfg:
val_dataset_cfg:
    <<: *dataset_cfg
