configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/ngpt.yaml # network model configuration
    - configs/datasets/dnerf_synthetic/jumpingjacks.yaml # dataset usage configuration
    #- configs/specs/static.yaml # specific usage configuration
    #- configs/specs/mask.yaml # specific usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
