configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/ngpt.yaml # network model configuration
    - configs/datasets/renbody/0013_09.yaml # dataset usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
