configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/r4dv.yaml # network model configuration
    - configs/datasets/renbody/0013_01_obj.yaml # dataset usage configuration
    - configs/specs/mask.yaml # specific usage configuration
    - configs/specs/optimized.yaml # specific usage configuration
    - configs/datasets/renbody/ratio.yaml

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}