benchmark: False # only perform benchmarking when training
# deterministic: True # set cudnn backend to deterministic mode
#dataloader_cfg: &dataloader_cfg
dataset_cfg: &dataset_cfg
    use_masks: True
    # use_vhulls: True # defaults to true
    immask_crop: True
    imbound_crop: True

val_dataset_cfg:
    <<: *dataset_cfg
    # FIXME: Now only declaring mask.yaml will not automatically change the validataion dataloader's background color

model_cfg:
    supervisor_cfg:
        msk_loss_weight: 0.001
